--- #YAML:1.0
name:               SQLib
version:            0.05
abstract:           A simple module to manage and store SQL queries in separate files.
author:
    - Mateusz Szczyrzyca <mateusz@szczyrzyca.pl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
